name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: üß∞ Configurar cache do Composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: üì¶ Configurar cache do NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: üé® Instalar e compilar assets frontend
        run: |
          npm ci --prefer-offline --no-audit
          npm run production

      - name: üì§ Enviar arquivos para a VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/ellonsports"
          strip_components: 0
          exclude: |
            .git
            .github
            node_modules
            .env
            .env.*
            *.log
            .idea
            .vscode
            .fleet
            .zed
            .nova
            Homestead.json
            Homestead.yaml
            auth.json
            .phpunit.cache
            .phpunit.result.cache
            .phpactor.json
            storage/*.key
            storage/pail
            public/hot
            public/storage
            vendor

      - name: üß® Executar comandos no servidor (deploy)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |

            cd /var/www/ellonsports

            echo "üì¶ Instalando depend√™ncias do Composer..."
            set -e
            composer install --no-interaction --no-dev --optimize-autoloader

            echo "‚ö° Executando migra√ß√µes..."
            php artisan migrate --force

            echo "üîê Liberando permiss√µes..."
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            echo "üßπ Limpando cache..."
            php artisan optimize:clear

            echo "‚ö° Otimizando aplica√ß√£o..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache

            echo "üîÑ Recarregando servi√ßos..."
            sudo systemctl reload php8.2-fpm

            echo "‚úÖ Deploy finalizado com sucesso!"
